products/urls.py
from django.conf.urls import patterns, url
from django.shortcuts import render
from products import views

urlpatterns = patterns('',
	url(r'^$', views.search, name = "search"),
	url(r'^new/$', views.newproduct, name = "new"),
	url(r'^_getvalues/$', views._get_values, name = "ajaxvalues"),
	url(r'^temp/$', views.temp, name = "temp"),
	url(r'^_getattributes/$', views._get_attributes, name = "ajaxattributes"),
	url(r'^(?P<product_code>.+)/editprice/(?P<price_id>\d+)/$', views.editprice, name = "editprice"),
	url(r'^(?P<product_code>.+)/newprice/$', views.editprice, name = "newprice"),
	url(r'^(?P<product_code>.+)/$', views.detail, name = "detail"),
)

urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
	url(r'^clients/', include('clients.urls', namespace="clients")),
	url(r'^products/', include('products.urls', namespace="products")),
    # Examples:
    # url(r'^$', 'tinyerp.views.home', name='home'),
    # url(r'^tinyerp/', include('tinyerp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

products/models.py
from django.db import models
from decimal import Decimal
from datetime import date

# Create your models here.

class UnitMeasurement (models.Model):
	symbol = models.CharField (max_length = 3)
	name = models.CharField (max_length = 20)
	value_int = models.IntegerField ()
	def __unicode__ (self):
		return self.name

class Attribute (models.Model):	
	attribute = models.CharField (max_length = 30)
	value = models.CharField (max_length = 30)
	class Meta:
		unique_together = ('attribute', 'value',)

	def to_dict (self):
		return {self.attribute: self.value}

TYPECHOICE = (
	(0, 'FORMATERIA'),
	(1, 'SELLOS'),
	(2, 'OTROS'),
)

class Name (models.Model):
	name = models.CharField (max_length = 50)
	type_product = models.IntegerField(choices=TYPECHOICE)

class Product (models.Model):
	name = models.ForeignKey (Name)
	code = models.CharField (max_length=10, unique=True)
	ranking = models.IntegerField (db_index=True, default=0)

class ProductAttributes (models.Model):
	product = models.ForeignKey (Product)
	attribute = models.ForeignKey (Attribute)
	class Meta:
		unique_together = ('product', 'attribute',)

class Price (models.Model):
	price = models.DecimalField (max_digits = 10, decimal_places = 2)
	unit = models.ForeignKey (UnitMeasurement)
	product = models.ForeignKey (Product)
	quantity = models.DecimalField(max_digits=8, decimal_places=2, default=1)
	min_initial_payment = models.DecimalField (max_digits = 10, decimal_places = 2, blank = True, null = True)

products/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import *

class SearchForm(forms.ModelForm):
	class Meta:
		model = Name
		exclude = ("type_product",)
	name = forms.CharField(widget = forms.TextInput(attrs = {'id':'input_name', 'placeholder':'Nombre del Producto', 'class':'form-control'}))
	# type_product = forms.ChoiceField(widget=forms.Select(attrs = {'id':'select_type_product', 'class':'form-control'}), choices=TYPECHOICE)
	description = forms.CharField(widget = forms.TextInput(attrs = {'id':'input_description', 'placeholder':'Descripcion', 'class':'form-control'}))


class NewProductForm (forms.ModelForm):
	name = forms.CharField(widget = forms.TextInput(attrs = {'id':'input_name', 'placeholder':'Nombre del Producto', 'class':'form-control'}))
	type_product = forms.ChoiceField(widget=forms.Select(attrs = {'id':'select_type_product', 'class':'form-control'}), choices=TYPECHOICE)
	code = forms.CharField(widget = forms.TextInput(attrs = {'id':'input_code', 'placeholder':'Código del Producto', 'class':'form-control'}))
	class Meta:
		model = Name

	def clean(self):
		super (NewProductForm, self).clean()
		code = self.cleaned_data.get('code')
		if len(Product.objects.filter (code = code)) > 0:
			 raise forms.ValidationError("El Código ya se encuentra asignado para otro producto")
		return self.cleaned_data

class EditPriceForm (forms.ModelForm):
	class Meta:
		model = Price
		exclude = ("product",)

	unit = forms.ModelChoiceField(queryset=UnitMeasurement.objects.all(), empty_label=None, widget=forms.Select(attrs = {'id':'select_unit', 'class':'form-control'}))
	quantity = forms.DecimalField(widget = forms.TextInput(attrs = {'id':'input_price', 'placeholder':u'Cant.', 'class':'form-control'}))
	price = forms.DecimalField(widget = forms.TextInput(attrs = {'id':'input_price', 'placeholder':u'Precio', 'class':'form-control input-right'}))
	min_initial_payment = forms.DecimalField(widget = forms.TextInput(attrs = {'id':'ti_min_initial', 'placeholder':u'Acta. Min', 'class':'form-control input-right'}))

	def __init__ (self, product, is_new, *args, **kwargs):
		self.product = product
		self.is_new = is_new
		super (EditPriceForm, self).__init__(*args, **kwargs)

	def clean (self):
		super (EditPriceForm, self).clean()
		initial = self.cleaned_data.get('min_initial_payment')
		price = self.cleaned_data.get('price')
		if self.is_new:
			qty = self.cleaned_data.get('quantity')
			unit = self.cleaned_data.get('unit')
			instances = Price.objects.filter (quantity = qty, unit = unit, product = self.product)
			if len(instances) > 0:
				raise forms.ValidationError("Ya existe un registro con la misma cantidad y unidad")
		if initial > price:
			raise forms.ValidationError("El valor mínimo de A cuenta no puede ser mayor al importe Total")
		return self.cleaned_data

	def save(self, product_id, commit = True):
		instance = forms.ModelForm.save(self, False)
		instance.product = product_id
		instance.save()
		return instance

products/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from models import *
from forms import SearchForm, EditPriceForm, NewProductForm
from helpers.ajax import ajax_view, AjaxError, ajax_simple

@ajax_simple
def _get_values (request):
	attr = request.GET.get('attr', 'COPIAS')
	values = Attribute.objects.filter(attribute = attr)
	values = [i.value for i in values]
	return values

@ajax_simple
def temp(request):
	attr = request.GET.get('attr', 'COPIAS')
	values = Attribute.objects.filter(attribute = attr)
	values = [i.value for i in values]
	return values

def _attributes (product_type):
	if product_type == 'FORMATERIA':
		return ['COPIAS', 'COLORES', 'MATERIAL', 'TAMANO', 'NUMERACION']
	if product_type == 'SELLOS':
		return ['PORTASELLO']
	else: 
		return ['COLORES', 'MATERIAL', 'ACABADO', 'TAMANO', 'TROQUELADO', 'NUMERACION']

@ajax_simple
def _get_attributes (request):
	product_type = request.GET.get('product_type', 'FORMATERIA')
	return _attributes(product_type)

def _get_description (product):
	desc = ProductAttributes.objects.filter(product = product)
	tmp = ""
	for d in desc: tmp += "%s, " % (d.attribute.value)
	return tmp

def delete_price(request, product_id):	
	instance = get_object_or_404(ProductPrice, pk=request.GET.get('product_price_id', ''))
	instance.delete()
	return { 'res': 'ok', 'action':reverse ('products:detail', args=[product_id]) }

def detail (request, product_code):
	product = get_object_or_404(Product, code=product_code)
	description = _get_description(product)
	prices = Price.objects.filter(product = product)
	return render(request, 'products/detail.html', {'product':(product, description), 'prices': prices})

def editprice (request, product_code, price_id = ''):	
	product = get_object_or_404(Product, code=product_code)
	description = _get_description(product)
	if price_id != '':
		price_instance = Price.objects.get(pk = price_id)
		action = reverse('clients:edit', args=[price_id] )
	else:
		price_instance = None
		action = reverse('clients:new')
	if request.method == 'POST':
		form_price = EditPriceForm (data = request.POST, instance = price_instance, product = product, is_new = price_instance == None)
		if form_price.is_valid():
			form_price.save(product)
			return HttpResponseRedirect( reverse ('products:detail', args =[product_code] ) )
	else:
		form_price = EditPriceForm (instance = price_instance, product = product, is_new = True)
	return render (request, 'products/editprice.html', {'form_price':form_price, 'product':product, 'description':description})

def newproduct (request):
	if request.method == 'POST':
		form_product = NewProductForm(request.POST)
		if form_product.is_valid():
			type_product = dict(form_product.fields['type_product'].choices)[int(form_product.cleaned_data.get('type_product'))]
			attrs = _attributes(type_product)
			name, created = Name.objects.get_or_create(name = form_product.cleaned_data.get('name').upper(),type_product = form_product.cleaned_data.get('type_product'))
			product, created = Product.objects.get_or_create (name = name, code = form_product.cleaned_data.get('code').upper())
			for attr in attrs:
				attribute, created = Attribute.objects.get_or_create(attribute = attr.upper(), value = request.POST.get(attr).upper())
				ProductAttributes.objects.create(attribute = attribute, product = product)
			return HttpResponseRedirect( reverse ('products:search' ) )
	else:
		form_product = NewProductForm()
	return render(request, 'products/newproduct.html', {'form_product':form_product})

def search (request):
	name = ""
	description = ""
	type_product = -1
	context = {}
	if request.method == 'POST':
		name, description, type_product = request.POST.get('name'), request.POST.get('description'), request.POST.get('type_product')
		context['fieldsearch'] = name + " " + description	
	description = description.upper().split()
	limit = 20
	products = Product.objects.filter(name__name__icontains = name).order_by('-ranking')[:limit]
	data = []
	for product in products:
		desc = ProductAttributes.objects.filter(product = product)
		tmp = _get_description(product)
		append_data = True
		for term in description:
			if term not in tmp: append_data = False
		if append_data: data.append( (product, tmp) )
	form = SearchForm()
	context['data'] = data
	context['form'] = form
	return render(request, 'products/search.html', context)

themes/templates/products/detail.html
{% extends "base.html" %}

{% block title %}Detalles de Producto{% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="main.html">Home</a></li>
  <li><a href="{% url 'products:search' %}">Productos</a></li>
  <li class="active">Ver producto</li>
</ol>
<div class="well well-lg">
	<div class="btn-group">
		<button class="btn btn-primary" type="button"><i class="fa fa-edit"></i> Editar Producto</button>
		<button class="btn btn-primary" type="button"><i class="fa fa-print"></i> Imprimir</button>
		<button class="btn btn-danger" type="button"><i class="fa fa-trash-o"></i> Eliminar Producto</button>
	</div>
	<div class="btn-group">
		<a href="{% url 'products:newprice' product.0.code %}" class="btn btn-primary"><i class="fa fa-plus"></i> Agregar Precio</a>
	</div>
	<hr/>
	<div class="row">
		<div class="col-md-6">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Información del Producto</h3>
				</div>
				<div class="panel-body">
					<strong>{{product.0.name.name}}</strong><br>
					<table class="table table-responsive table-user-information">
						<tr>
							<td>Descripción:</td>
							<td>{{product.1}}</td>
						</tr>
						<tr>
							<td>Ranking:</td>
							<td>{{product.0.ranking}}</td>
						</tr>
						<tr>
							<td>Código:</td>
							<td>{{product.0.code}}</td>
						</tr>
					</table>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Precios</h3>
				</div>
				<div class="panel-body">
					{% if prices %}
					<table class="table table-responsive table-user-information">
						<thead>
						<tr>
							<td><strong>Cantidad</strong></td>
							<td><strong>Unidad</strong></td>
							<td><strong>Acta. Mín</strong></td>
							<td><strong>Precio</strong></td>
						</tr>
						</thead>
						<tbody>
						{% for price in prices %}
						<tr>
							<td>{{price.quantity}}</td>
							<td>{{price.unit.name}}</td>
							<td>S/. {{price.min_initial_payment}}</td>
							<td>S/. {{price.price}}</td>
							<td><a id="a_edit_{{price.pk}}" class="btn btn-xs btn-primary a_edit" href
								="{% url 'products:editprice' product.0.code price.pk %}"><i class="fa fa-pencil"></i></a> <a id="a_delete_{{price.pk}}" class="btn btn-xs btn-danger a_delete" href="#"><i class="fa fa-trash-o"></i></a></td>
						</tr>
						{% endfor %}
					</table>
					{% else %}
					<p><em>No existe ningún precio asignado.</em></p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

themes/templates/products/editprice.html
{% extends "base.html" %}

{% block title %}Detalles de Producto{% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="main.html">Home</a></li>
  <li><a href="{% url 'products:search' %}">Productos</a></li>
  <li><a href="javascript:history.back()">{{product.name.name}}</a></li>
  <li class="active">Agregar Precio</li>
</ol>
<h2>Nuevo Precio</h2>
<h4>{{product.name.name}}</h4>
<h5>{{description}}</h5>
<hr/>
{% if form_price.errors %}
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong>Algunos errores han ocurrido!</strong> El precio del producto no puede ser menor al precio del acuenta, o ya existe un precio con las mismas características para el producto.
</div>
{% endif %}
<form class="form-horizontal" role="form" method="POST"> {% csrf_token %}
  <div class="form-group">
	<label for="inputEmail3" class="col-sm-2 control-label">Cantidad</label>
	<div class="col-sm-1">
	  {{ form_price.quantity }}
	</div>
  </div>
  <div class="form-group">
	<label for="inputEmail3" class="col-sm-2 control-label">Unidad</label>
	<div class="col-sm-2">
	  {{ form_price.unit }}
	</div>
  </div>
  <div class="form-group">
	<label for="inputEmail3" class="col-sm-2 control-label">Precio S/.</label>
	<div class="col-sm-2">
		<div class="input-group">
			{{ form_price.price }}
			<span class="input-group-addon">.00</span>
		</div>
	</div>
  </div>
  <div class="form-group">
	<label for="inputEmail3" class="col-sm-2 control-label">A cuenta Mínimo S/.</label>
	<div class="col-sm-2">
	 	<div class="input-group">
			{{ form_price.min_initial_payment }}
			<span class="input-group-addon">.00</span>
		</div>
	</div>
  </div>		  
  <div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
	  <button type="submit" class="btn btn-primary">Guardar</button>
	  <button type="reset" class="btn btn-warning">Limpiar</button>
	</div>
  </div>
</form>
{% endblock %}

themes/templates/products/newproduct.html
{% extends "base.html" %}

{% block title %}Nuevo Producto{% endblock %}

{% block content %}
<script type="text/javascript">
$(function(){
	var url_remote = '{% url "products:ajaxvalues" %}' + '?attr=';
	function create_typeahead(input_id){
		var dom_object = '<div class="form-group"> <label class="col-sm-2 control-label">'+ input_id + '</label> <div class="col-sm-3"> <input class="typeahead form-control" name="' + input_id + '" id="' + input_id + '" placeholder="Num. Copias" /> </div> </div>'
		$('#attributes').append(dom_object);
		$('input.typeahead#' + input_id ).typeahead({
			name: input_id,
			remote: url_remote + input_id
		});
	}
	function get_attributes(){
		var product_type = $('#select_type_product option:selected').text();
		$.ajax("{% url 'products:ajaxattributes' %}", {
			type: 'get',
			dataType: 'json',
			data: {'product_type': product_type},
			success: function (res) {
				$('#attributes').empty();
				res.forEach(function(i){
					create_typeahead(i);
				});
			}
		});
	}
	get_attributes();
	$('#select_type_product').bind('change', function(){get_attributes();});
});
</script>

<ol class="breadcrumb">
  <li><a href="main.html">Home</a></li>
  <li><a href="javascript:history.back()">Productos</a></li>
  <li class="active">Agregar</li>
</ol>
<h2>Nuevo Producto</h2>
<hr/>
<form class="form-horizontal" action="{% url 'products:new' %}" method="post"> {% csrf_token %}
  <div class="form-group">
	<label class="col-sm-2 control-label">Nombre</label>
	<div class="col-sm-5">
	  {{form_product.name}}
	</div>
  </div>
  <div class="form-group">
	<label class="col-sm-2 control-label">Tipo</label>
	<div class="col-sm-3">
	  {{form_product.type_product}}
	</div>
  </div>
  <div class="form-group">
	<label class="col-sm-2 control-label">Codigo</label>
	<div class="col-sm-2">
	  {{form_product.code}}
	</div>
  </div>
<hr />
  <div id="attributes"></div>
  <div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
	  <button type="submit" class="btn btn-primary">Guardar</button>
	  <button type="reset" class="btn btn-warning">Limpiar</button>
	</div>
  </div>
</form>
{% endblock %}

themes/templates/products/search.html
{% extends "base.html" %}

{% block title %}Productos{% endblock %}

{% block content %}

<ol class="breadcrumb">
	<li><a href="main.html">Home</a></li>
	<li class="active">Productos</li>
</ol>
<div> <a href="{% url 'products:new' %}" class="btn btn-primary">+ Nuevo Producto</a></div>
<hr />
<div> 
<form class="form-inline" role="form" method="POST"> {% csrf_token %}
	<div class="form-group col-sm-3">
		{{form.name}}
	</div>
	<div class="form-group col-sm-6">
		{{form.description}}
	</div>
	<button type="submit" class="btn btn-default"><i class="fa fa-search"></i> Buscar</button>
</form>
<br>
</div>
<div class="panel panel-success">
	<!-- Default panel contents -->
	<div class="panel-heading">
		{% if fieldsearch %}
		Mostrando los resultados de <em><strong>{{fieldsearch}}</strong></em>.
		{% else %}
		Mostrando los <strong> 20 mejores resultados</strong>.
		{% endif %}
	</div>		
		<div class="panel-body">
		  {% if data|length > 0 %}
		  <p><em>{{data|length}} resultado(s).</em></p>
		  <table class="table table-hover">
			<thead>
			  <tr>
				<th width="5%">Código</th>
				<th width="20%">Nombre</th>
				<th>Descripción</th>
			  </tr>
			</thead>
			<tbody>
			  {% for elem in data%}
			  <tr>
				<td><a href="{% url 'products:detail' elem.0.code %}">{{elem.0.code}}</a></td>
				<td>{{elem.0.name.name}}</td>
				<td>{{elem.1}}</td>
			  </tr>
			  {% endfor %}			  
			</tbody>
		  </table>
		  {% else %}
		  <p><em>No se encontrarón resultados.</em></p>
		  {% endif %}
	  </div>
	</div>
</div>
{% endblock %}