clients/urls.py
from django.conf.urls import patterns, url
from django.shortcuts import render
from clients import views
from clients.views import ClientListJSON

urlpatterns = patterns('',
	url(r'^$', views.all, name = "all"),
	url(r'^(?P<client_id>\d+)/$', views.detail, name = "detail"),
	url(r'^edit/(?P<client_id>\d+)/$', views.edit, name = "edit"),
	url(r'^_get_districts/$', views._get_districts, name = "getdistricts"),
	url(r'^_get_jsonlist/$', ClientListJSON.as_view(), name = "jsonlist"),
	url(r'^_get_provinces/$', views._get_provinces, name = "getprovinces"),
	url(r'^new/$', views.edit, name = "new"),
)

urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
	url(r'^clients/', include('clients.urls', namespace="clients")),
	url(r'^products/', include('products.urls', namespace="products")),
    # Examples:
    # url(r'^$', 'tinyerp.views.home', name='home'),
    # url(r'^tinyerp/', include('tinyerp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

clients/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.db import models
from domiciles.models import Domicile

# Create your models here.

class Client (models.Model):
	ruc = models.CharField (max_length = 11, primary_key = True)
	razon_social = models.CharField (max_length = 200)
	email = models.EmailField (max_length = 100, blank = True, null = True)
	telephone = models.CharField (max_length = 9, blank = True, null = True)
	domicile = models.OneToOneField (Domicile)

	def __unicode__ (self):
		return '%s: %s' % (self.ruc, self.razon_social)

	def to_dict (self):
		return {'ruc': self.ruc, 'razon_social': self.razon_social, 'domicile':self.domicile.toString() }

clients/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from models import Client

class ClientForm(forms.ModelForm):
	ruc = forms.CharField(widget = forms.TextInput(attrs = {'id':'input_ruc', 'placeholder':'RUC', 'maxlength':11, 'class':'form-control'}))
	razon_social = forms.CharField(widget = forms.TextInput(attrs = {'id':'input_razon_social', 'placeholder':u'Razón Social', 'class':'form-control'}))
	email = forms.EmailField(required=False, widget = forms.TextInput(attrs = {'id':'input_email', 'placeholder':'Email', 'class':'form-control'}))
	telephone = forms.CharField(required=False, widget = forms.TextInput(attrs = {'id':'input_telephone', 'placeholder':u'Teléfono', 'class':'form-control'}))
	class Meta:
		model = Client
		exclude = ('domicile')

clients/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponseRedirect
from models import Client, Domicile
from forms import ClientForm
from domiciles.forms import DomicileForm
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.forms.models import model_to_dict
from django.db.models import Q
from django.core.urlresolvers import reverse
from helpers.ajax import ajax_view, AjaxError

dpd = {'AREQUIPA':{
		'AREQUIPA':['AREQUIPA', 'ALTO SELVA ALEGRE', 'CAYMA', 'JACOBO HUNTER', 'JOSE LUIS BUSTAMANTE Y RIVERO', 'MARIANO MELGAR', 'MIRAFLORES', 'PAUCARPATA','YANAHUARA'],
		'ISLAY':[ 'LA JOYA', 'MAJES', 'VITOR']
		}
	  }

@ajax_view
def _get_provinces (request):
	department = request.GET.get('department', 'AREQUIPA')
	try: provinces = dpd[department].keys()
	except: provinces = []
	return { 'provinces' : provinces }

@ajax_view
def _get_districts (request):
	department = request.GET.get('department', 'AREQUIPA')
	province = request.GET.get('province', 'AREQUIPA')
	try: districts = dpd[department][province]
	except: districts = []
	return { 'districts' : districts }

def all (request):
	client_list = ClientListJSON()
	client_list.request = request
	data = client_list.get_context_data()
	return render(request, 'clients/all.html', {'data': data})

def detail(request, client_id):
	client = get_object_or_404(Client, pk=client_id)
	return render(request, 'clients/detail.html', {'client':client})

# Create your views here.
def edit(request, client_id = ''):
	if client_id != '':
		client_instance = Client.objects.get(pk = client_id)
		domicile_instance = Domicile.objects.get(pk = client_instance.domicile_id)
		action = reverse('clients:edit', args=[client_id] )
	else:
		client_instance = None
		domicile_instance = None
		action = reverse('clients:new')
	if request.method == 'POST':
		department, province, district = request.POST.get('department'), request.POST.get('province'), request.POST.get('district')
		form_client = ClientForm (request.POST, instance = client_instance )
		form_domicile = DomicileForm (request.POST, instance = domicile_instance )
		if form_client.is_valid() and form_domicile.is_valid():
			d = form_domicile.save(commit = False)
			d.department, d.province, d.district = department, province, district
			d.save()
			client = form_client.save(commit = False)
			client.domicile = d
			client.save()
			return HttpResponseRedirect( reverse ('clients:detail', args =[client.ruc] ) )
	else:		
		form_client = ClientForm (instance = client_instance)
		form_domicile = DomicileForm (instance = domicile_instance)
	return render (request, 'clients/edit.html', {'form_client':form_client, 'form_domicile':form_domicile, 'action':action, 'departments':dpd.keys(), 'provinces':sorted(dpd['AREQUIPA'].keys()), 'districts':dpd['AREQUIPA']['AREQUIPA']})

class ClientListJSON(BaseDatatableView):
	model = Client
	columns = ['ruc', 'razon_social', 'telephone', 'email']
	order_columns = ['ruc', 'razon_social', 'telephone', 'email']
	max_display_length = 100
	def render_column(self, row, column):		
		if column == 'ruc':
			return '<a href="/clients/%s"> %s </a>' % (row.ruc, row.ruc)
		else:
			return super(ClientListJSON, self).render_column(row, column)

	def filter_queryset(self, qs):
		sSearch = self.request.GET.get('sSearch', None)
		if sSearch:
			qs = qs.filter(Q(razon_social__istartswith=sSearch) | Q(ruc__istartswith=sSearch))
		return qs

themes/templates/clients/all.html
{% extends "base.html" %}

{% block title %}Todos los clientes{% endblock %}

{% block content %}
<script type="text/javascript">
$(function(){
	function load_clients (id_table, ajax_source){
		var oTable = $(id_table).dataTable({
			"bProcessing": true,
			"bServerSide": true,
			"sAjaxSource": ajax_source,
			"sServerMethod": "GET",
			"aoColumns": [
			{ "sWidth": "10%" },
			{ "sWidth": "60%" },
			{ "sWidth": "10%", "sClass": "center", "bSortable": false }, 
			{ "sWidth": "20%", "sClass": "center", "bSortable": false },
			],
			"fnRowCallback": function(nRow, aData, iDisplayIndex, iDisplayIndexFull) {
				$(nRow).click(function(){
					click_fn(nRow, aData, iDisplayIndex, iDisplayIndexFull);
				});
			}
		});
		$(id_table + ' tbody tr').bind('click', function(){
			alert( 'jaja')
		});
		// function clickRowHandler() {
		// 	$('#sku_tbl tbody tr').bind('click', function () {
		// 		var aData = oTable.fnGetData( this );
		// 		var iId = aData[0];
		// 		alert ("jojo");
		// 	});
		// }
	}
	load_clients ( '#clients-table', "{% url 'clients:jsonlist' %}" );
});

</script>

<ol class="breadcrumb">
  <li><a href="main.html">Home</a></li>
  <li class="active">Clientes</li>
</ol>
<div>
	<a href="{% url 'clients:new' %}" class="btn btn-primary"><i class="fa fa-plus"></i> Nuevo Cliente</a>
</div>
<hr />
<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">Todos los clientes</div>
		<div class="panel-body">
			<p> <em>Incluir data tables y darle el mismo estilo</em></p>
			  <table id="clients-table" class="table table-hover table-condensed">
				<thead>
					<tr>						
						<th>RUC</th>
						<th>Razon Social</th>
						<th>Teléfono</th>
						<th>Email</th>
					</tr>
				</thead>
				<tbody> </tbody>
			  </table>
	  </div>
	</div>
</div>
{% endblock %}

themes/templates/clients/detail.html
{% extends "base.html" %}

{% block title %}Detalles de Cliente{% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="main.html">Home</a></li>
  <li><a href="{% url 'clients:all' %}">Clientes</a></li>
  <li class="active">Ver perfil</li>
</ol>
<div class="well well-lg">
	<div class="btn-group">
		<button class="btn btn-primary" type="button" data-toggle="tooltip" data-original-title="Send message to user"><i class="fa fa-list-alt"></i> Ventas del Cliente</button>
		<a href="{% url 'clients:edit' client.ruc  %}" class="btn btn-primary" type="button" data-toggle="tooltip" data-original-title="Edit this user"><i class="fa fa-edit"></i> Editar Cliente</a>
		<button class="btn btn-primary" type="button" data-toggle="tooltip" data-original-title="Edit this user"><i class="fa fa-print"></i> Imprimir</button>
		<button class="btn btn-danger" type="button" data-toggle="tooltip" data-original-title="Remove this user"><i class="fa fa-trash-o"></i> Eliminar Cliente</button>
	</div>
	<hr/>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Información del Cliente</h3>
		</div>
		<div class="panel-body">
			<strong>{{ client.razon_social }}</strong><br>
			<table class="table table-responsive table-user-information">
				<thead>
				<tr>
					<td style="width:200px">RUC:</td>
					<td>{{client.ruc}}</td>
				</tr>
				</thead>
				<tbody>
				<tr>
					<td>Dirección:</td>
					<td>{{ client.domicile.address }} - {{ client.domicile.district }} - {{ client.domicile.province }} - {{ client.domicile.department }}</td>
				</tr>
				<tr>
					<td>Teléfono:</td>
					<td>{{ client.telephone }}</td>
				</tr>
				<tr>
					<td>Emails</td>
					<td>{{ client.email }}</td>
				</tr>
				</tbody>
			</table>
		</div>					
	</div>
</div>
{% endblock %}

themes/templates/clients/edit.html
{% extends "base.html" %}

{% block title %}Add a Client{% endblock %}

{% block content %}
<ol class="breadcrumb">
  <li><a href="main.html">Home</a></li>
  <li><a href="{% url 'clients:all' %}">Clientes</a></li>
  <li class="active">Agregar</li>
</ol>

<script type="text/javascript">
	$(function(){
		var change_provinces = function(new_provinces){
			$('#select_province').empty();
			for (var i = 0; i < new_provinces.length; ++i)
				$('#select_province').append("<option>"+new_provinces[i]+"</option>")
		};
		var change_districts = function(new_districts){
			$('#select_district').empty();
			for (var i = 0; i < new_districts.length; ++i)
				$('#select_district').append("<option>"+new_districts[i]+"</option>")
		};
		var null_select = "----------";
		
		$('#select_department').bind('change', function(){
			var opt_val = $('#select_department').val();
			if (opt_val == null_select) return false;
			$.ajax("{% url 'clients:getprovinces' %}", {
				type: 'get',
				dataType: 'json',
				data: {'department': opt_val},
				success: function (res) { change_provinces(res.response.provinces); }
			});
		});
		$('#select_province').bind('change', function(){
			var opt_val = $('#select_province').val();
			if (opt_val == null_select) return false;
			var department = $('#select_department').val();
			$.ajax("{% url 'clients:getdistricts' %}", {
				type: 'get',
				dataType: 'json',
				data: {'province': opt_val, 'department':department},
				success: function (res) { change_districts(res.response.districts); }
			});
		});
	});
</script>

<h2>Nuevo Cliente</h2>
<hr/>
{{ form_client.errors }}
{{ form_domicile.errors }}
<form class="form-horizontal" role="form" method="POST"> {% csrf_token %}
  <div class="form-group">
	<label for="inputEmail3" class="col-sm-2 control-label">RUC</label>
	<div class="col-sm-3">
		{{ form_client.ruc }}
		<span class="text-danger"> {{ form_client.ruc.errors }} </span>
	</div>

  </div>
  <div class="form-group">
	<label for="inputPassword3" class="col-sm-2 control-label">Razón Social</label>
	<div class="col-sm-10">
		{{ form_client.razon_social }}
		<span class="text-danger"> {{ form_client.razon_social.errors }} </span>
	</div>
  </div>
  <hr />
  <h3>Domicilio</h3>
  <div class="form-group">
	<label class="col-sm-2 control-label">Domicilio</label>
	<div class="col-sm-10">
		{{ form_domicile.address }}
		<span class="text-danger"> {{ form_domicile.address.errors }} </span>
	</div>
  </div>
  <div class="form-group">
	<label class="col-sm-2 control-label">Dist / Prov / Dept</label>
	<div class="col-sm-3">
		<select id="select_department" class="form-control" name="department">		  	
		{% for department in departments %}
	  		{% if form_domicile.department.value == department %} <option selected>{{ department }}</option>
			{% else %}<option>{{ department }}</option>
			{% endif %}
		{% endfor %}
		</select>
	</div>
	<div class="col-sm-3">
		<select id="select_province" class="form-control" name="province">
		{% for province in provinces %}
			{% if form_domicile.province.value == province %} <option selected>{{ province }}</option>
			{% else %}<option>{{ province }}</option>
			{% endif %}
		{% endfor %}
		</select>
	</div>
	<div class="col-sm-3">
		<select id="select_district" class="form-control" name="district">
		{% for district in districts %}
			{% if form_domicile.district.value == district %} <option selected>{{ district }}</option>
			{% else %}<option>{{ district }}</option>
			{% endif %}
		{% endfor %}
		</select>
	</div>
  </div>
  <div class="form-group">
	<label for="inputEmail3" class="col-sm-2 control-label">Teléfono</label>
	<div class="col-sm-3">
	  	{{ form_client.telephone }}
		<span class="text-danger"> {{ form_client.telephone.errors }} </span>
	</div>
	<label for="inputEmail3" class="col-sm-2 control-label">Email</label>
	<div class="col-sm-5">
	  	{{ form_client.email }}
		<span class="text-danger"> {{ form_client.telephone.errors }} </span>
	</div>
  </div>
  <div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
	  <button type="submit" class="btn btn-primary">Guardar</button>
	  <button type="reset" class="btn btn-warning">Limpiar</button>
	</div>
  </div>
</form>
{% endblock %}