clients/urls.py
from django.conf.urls import patterns, url
from django.shortcuts import render
from clients import views
from clients.views import ClientListJSON

urlpatterns = patterns('',
	url(r'^$', views.all, name = "all"),
	url(r'^(?P<client_id>\d+)/$', views.detail, name = "detail"),
	url(r'^edit/(?P<client_id>\d+)/$', views.edit, name = "edit"),
	url(r'^_get_districts/$', views._get_districts, name = "getdistricts"),
	url(r'^_get_jsonlist/$', ClientListJSON.as_view(), name = "jsonlist"),
	url(r'^_get_provinces/$', views._get_provinces, name = "getprovinces"),
	url(r'^new/$', views.edit, name = "new"),
)

products/urls.py
from django.conf.urls import patterns, url
from django.shortcuts import render
from products import views

urlpatterns = patterns('',
	url(r'^$', views.search, name = "search"),
	url(r'^new/$', views.newproduct, name = "new"),
	url(r'^_getvalues/$', views._get_values, name = "ajaxvalues"),
	url(r'^temp/$', views.temp, name = "temp"),
	url(r'^_getattributes/$', views._get_attributes, name = "ajaxattributes"),
	url(r'^(?P<product_code>.+)/editprice/(?P<price_id>\d+)/$', views.editprice, name = "editprice"),
	url(r'^(?P<product_code>.+)/newprice/$', views.editprice, name = "newprice"),
	url(r'^(?P<product_code>.+)/$', views.detail, name = "detail"),
)

urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
	url(r'^clients/', include('clients.urls', namespace="clients")),
	url(r'^products/', include('products.urls', namespace="products")),
    # Examples:
    # url(r'^$', 'tinyerp.views.home', name='home'),
    # url(r'^tinyerp/', include('tinyerp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

themes/templates/base.html
<!doctype html>
<html lang="en">
<head>
	{% load compress %}
	<meta charset="UTF-8">
	{% compress css %}
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/DT_bootstrap.css" />
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/personalized-main.css" />
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/font-awesome.min.css" />
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/typeahead.css" />
	{% endcompress %}
	<script src="{{ STATIC_URL }}js/jquery-1.10.2.min.js"></script>
	<script src="{{ STATIC_URL }}js/jquery.dataTables.min.js"></script>
	<script src="{{ STATIC_URL }}js/DT_bootstrap.js"></script>
	<script src="{{ STATIC_URL }}js/typeahead.min.js"></script>
	<title>{% block title %}{% endblock %}</title>
	{% pageurl 'adsasdasd' %}
</head>
  <body>
	<!-- Fixed navbar -->
	<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	  <div class="container">
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </button>
		  <a class="navbar-brand" href="#">TinyERP</a>
		</div>
		<div class="navbar-collapse collapse">
		  <ul class="nav navbar-nav">		  	
			<li><a href="orders.html">Órdenes de Trabajo</a></li>
			<li class="dropdown">
			  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Ventas<b class="caret"></b></a>
			  <ul class="dropdown-menu">
			  	<li class="dropdown-header">Ventas</li>
				<li><a href="quotations.html">Presupuestos</a></li>
				<li><a href="invoices.html">Facturas</a></li>
			  </ul>
			</li>	
			<li><a href="{% url 'clients:all' %}">Clientes</a></li>
			<li><a href="{% url 'products:search' %}">Productos</a></li>
		  </ul>
		  <ul class="nav navbar-nav navbar-right">
			<li><a href="options.html">Opciones</a></li>
		  </ul>
		</div><!--/.nav-collapse -->
	  </div>
	</div>
	<div class="container">
		{% block content %}
		<ol class="breadcrumb">
		  <li>Home</li>
		</ol>
		{% endblock %}
	</div> <!-- /container -->
  </body>
</html>